apiVersion: v1
data:
  mapRoles: |
    groups:
      - system:masters
      rolearn: arn:aws:iam::149858864837:role/UdacityFlaskDeployCBKubectlRole
      username: build
    groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::149858864837:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1FBYXSR98ED9W
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-24T16:07:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1596"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c3e7c5d9-a967-4ed3-b6e8-d97cc46729eb